### PR TITLE
Fix usages of depset

### PR DESCRIPTION
**Pull request by laurentlb**
It would take more time and redesign to get a clean version. The code
has no owner, and probably not much usage, so I didn't want to spend too
much time. Also, it lacks tests.

Tested:
  `bazel test //... --all_incompatible_changes`

### CODE REVIEW

**Comment by meteorcloudy** [comment]
FYI, rules_d has been removed from downstream because it doesn't have owner. https://github.com/bazelbuild/continuous-integration/commit/1a5de9b3a7b111360f757fb55535947fe57e561a#diff-9ca62ea3191ff346e911994ded260c87

**Comment by laurentlb** [comment]
Yes, but it's used by other repositories, e.g. rules_docker.

**Comment by meteorcloudy** [comment]
Oh... then maybe it's better to keep it in downstream?

**Comment by meteorcloudy** [comment]
Done. https://github.com/bazelbuild/continuous-integration/commit/51ce669157f7f30470ddbde08307ba4ebbaf1bfe

**Pull request merged**
