### PR TITLE
Use Bazel mirror to download tarballs

### PR DESCRIPTION
**Pull request by jart**
I've mirrored your files for guaranteed reliability, courtesy of Google Cloud Storage.

In the future, you can mirror these files too with the following command. Although you need to ask @damienmg for write access to the bucket. Or just email me the URL you want mirrored and I'll happily do it.

```bash
bzmirror() {
  local url="${1:?url}"
  if [[ "${url}" =~ ^([^:]+):([^:]+):([^:]+)$ ]]; then
    url="http://repo1.maven.org/maven2/${BASH_REMATCH[1]//.//}/${BASH_REMATCH[2]}/${BASH_REMATCH[3]}/${BASH_REMATCH[2]}-${BASH_REMATCH[3]}.jar"
  fi
  local dest="gs://bazel-mirror/${url#http*//}"
  local desturl="http://bazel-mirror.storage.googleapis.com/${url#http*//}"
  local name="$(basename "${dest}")"
  wget -O "/tmp/${name}" "${url}" || return 1
  gsutil cp -a public-read "/tmp/${name}" "${dest}" || return 1
  gsutil setmeta -h 'Cache-Control:public, max-age=31536000' "${dest}" || return 1
  curl -I "${desturl}"
  echo
  sha256sum "/tmp/${name}"
  echo "${desturl}"
  rm "/tmp/${name}" || return 1
}
```

### CODE REVIEW

**Comment by davidzchen** [comment]
Given the jgit issues that we have had, this seems reasonable to me. Can you also update the README to recommend using `http_archive` for adding the external repository for using this rule set? Thanks!

**Comment by jart** [comment]
@davidzchen Done. I did it as a second commit. So consider not squashing when you merge.

I also recommend cutting a 0.0.2 release sometime soon, since there appears to have been a bug fix since 0.0.1.

**Comment by jart** [comment]
Also are your jgit issues related to https://github.com/bazelbuild/bazel/issues/1515 ?

**Comment by davidzchen** [comment]
Yes, I was referring to the issues described in bazelbuild/bazel#1515. Thank you for doing the work to create the mirrors and opening all these PRs!

I prefer to not have extraneous merge commits in the revision history. If you would like to have a separate commit for the README change, can you open a PR for that?

**Comment by jart** [comment]
Feel free to squash it then.

**Comment by davidzchen** [comment]
Thanks.

**Pull request merged**
