### PR TITLE
Add some tests

### PR DESCRIPTION
**Pull request by dcarp**
This tests are meant to secure the current implementation and provide a basis to add new features.

### CODE REVIEW

**Comment by dcarp** [comment]
Please squash before merge.
Some more PRs will follow.

**Comment by laurentlb** [comment]
Thanks! The rules were mostly abandoned.
Now I'm curious: are you using them rules? Are you interested in being a maintainer?

I'm personally not familiar with the rules, and I've never used D. I can do the reviews though.

**Comment by dcarp** [comment]
> Thanks! The rules were mostly abandoned.
> Now I'm curious: are you using them rules? Are you interested in being a maintainer?

Yes, I'm really using them and I plan to bring them up to date. I also plan to add support for [LDC](https://wiki.dlang.org/LDC) and [GDC](https://www.gdcproject.org/).
I don't know if I qualify for that, but yes, I'm interested in maintaining `rules_d`.

> 
> I'm personally not familiar with the rules, and I've never used D. I can do the reviews though.

Thank you, your support is very much appreciated as I'm not a bazel expert.

Next step I'll add support for customizing the version of `dmd` compiler. So I'll add a parameter to `d_repositories` like `d_repositories(version="2.086")`. Is it the way to go? How would it look like if later I want to support `LDC` or `GDC` compilers? Should I add another `compiler` parameter for  `d_repository`, or select them using a platform rule?

**Comment by meteorcloudy** [comment]
This PR is causing rules_d to fail in downstream:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/972#b3fc4b49-e247-46f7-a2c7-0ab3175edd52
```
ERROR: /workdir/bazel-downstream-projects/rules_d/tests/c_library_usage_no_wrapper/BUILD:3:1: in d_test rule //tests/c_library_usage_no_wrapper:c_library_usage_no_wrapper:
--
  | Traceback (most recent call last):
  | File "/workdir/bazel-downstream-projects/rules_d/tests/c_library_usage_no_wrapper/BUILD", line 3
  | d_test(name = 'c_library_usage_no_wrapper')
  | File "/home/bazel/.cache/bazel/_bazel_bazel/4d87dae5a26f1372034960ad5d0a7249/external/io_bazel_rules_d/d/d.bzl", line 332, in _d_test_impl
  | _d_binary_impl_common(ctx, extra_flags = ["-unittest"])
  | File "/home/bazel/.cache/bazel/_bazel_bazel/4d87dae5a26f1372034960ad5d0a7249/external/io_bazel_rules_d/d/d.bzl", line 264, in _d_binary_impl_common
  | _setup_deps(ctx.attr.deps, ctx.label.name, d_bin...)
  | File "/home/bazel/.cache/bazel/_bazel_bazel/4d87dae5a26f1372034960ad5d0a7249/external/io_bazel_rules_d/d/d.bzl", line 188, in _setup_deps
  | libs += native_libs
  | `+` operator on a depset is forbidden. See https://docs.bazel.build/versions/master/skylark/depsets.html for recommendations. Use --incompatible_depset_union=false to temporarily disable this check.
```

Please help fix the incompatible change.

**Comment by dcarp** [comment]
Fixed in #27.

**Comment by laurentlb** [comment]
Great: the breakage shows that your tests were really useful. :)

**Comment by dcarp** [comment]
Right, thanks!

**Pull request merged**
